info:
  component: Api Gateway     

logging:
  level:
    ROOT: INFO
    org.springframework.web: INFO

hystrix.command.default.execution.isolation.strategy: SEMAPHORE
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 5000
hystrix.command.default.circuitBreaker.forceClosed: true
  
